# Generated by Django 3.2 on 2022-12-19 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='titlegenre',
            unique_together={('title', 'genre')},
        ),
    ]
