# Generated by Django 3.2 on 2022-12-15 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OneTitleOneReview',
        ),
    ]
