# Generated by Django 3.2 on 2022-12-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Заполните биографию пользователя', null=True, verbose_name='Биография пользователя'),
        ),
        migrations.AlterUniqueTogether(
            name='titlegenre',
            unique_together={('title', 'genre')},
        ),
    ]
