# Generated by Django 3.2 on 2022-12-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_delete_onetitleonereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Заполните биографию пользователя', null=True, verbose_name='Биография пользователя'),
        ),
    ]
