# Generated by Django 3.2 on 2022-12-20 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_titlegenre_unique_together'),
        ('reviews', '0002_auto_20221219_2140'),
    ]

    operations = [
    ]
